ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"


repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: name-tests-test
    args: ["--pytest-test-first"]

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.4.0
  hooks:
  - id: setup-cfg-fmt
    args: [--include-version-classifiers, --max-py-version=3.11]

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
  - id: black

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.291
  hooks:
  - id: ruff
    args: ["--fix", "--show-fixes"]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    args: ["-L", "ue,subjet,parms,fo,numer,thre,gaus"]

- repo: local
  hooks:
  - id: disallow-caps
    name: disallow improper capitalization
    language: pygrep
    entry: PyBind|Cmake|CCache|Github|PyTest
    exclude: .pre-commit-config.yaml

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: "v0.9.0.5"
  hooks:
  - id: shellcheck

- repo: https://github.com/asottile/pyupgrade
  rev: v3.13.0
  hooks:
  - id: pyupgrade
